name: BP_CI                                        # "bp_CI" workflow, name is optional

env:
  AZURE_WEBAPP_NAME: gc-bpcalculator-ga            # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: 'publish'              # set this to the path to your web app project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 

jobs:
  build:                                            # "build" job
    runs-on: windows-latest                         # runner
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
    - name: Build for Release
      run: dotnet build --configuration Release
      
      
    - name: Analyze code with SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: .
        args: >
          -Dsonar.organization=test
          -Dsonar.projectKey=bp
          -Dsonar.python.coverage.reportPaths=coverage.xml
          -Dsonar.verbose=true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
    - name: Run unit tests
      run: dotnet test TestProject1/TestProject1.csproj --no-restore --collect "Code coverage" -l:trx
   
    - name: Publish Unit Test Results
      uses: dorny/test-reporter@v1
      with:
        artifact: ''
        name: MS Tests                  
        path: '**.trx'
        reporter: 'dotnet-trx'                     

    - name: Publish
      run: dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' 
